### ISSUE TITLE
Bad interaction with Map Preview, Dubs Bad Hygiene, and Cleaning Priority.

### ISSUE THREAD

**Issue by MrXarous** [emipa606/CleaningPriority#3]
User Inglix reported this originally here https://discord.com/channels/680705672911913016/693732045100154910/1039235463598329856

https://gist.github.com/HugsLibRecordKeeper/0049a0367e0ec0200487629b23bfa744

Upon testing also confirmed of this issue
https://gist.github.com/012e8660779ed8e27a64deed29a556ea

Yellow text spam in log until max message reached and delays Map Preview's previews from loading promptly.

**Comment by emipa606** [comment]
Nice catch, should be fixed in 198ee57
