### ISSUE TITLE
ChineseSimplified Translation

### ISSUE THREAD

**Issue by Buyue-z** [emipa606/CleaningPriority#6]
In Keyed\CleaningPriority.xml

`<?xml version="1.0" encoding="utf-8"?>
<LanguageData>
  <OpenCleaningPriorityDialog>打开清洁优先级窗口。\n\n在这里，你可以设置殖民者优先清洁的区域、最后清洁的区域或介于两者之间的区域。</OpenCleaningPriorityDialog>
  <AddAreaAsCleaningArea>如果你对哪些区域被优先清洁感到困惑，请将鼠标悬停在列表中的区域上并阅读提示。</AddAreaAsCleaningArea>
  <AddAreaForPriorityCleaning>添加区域</AddAreaForPriorityCleaning>
  <AddAreaForPriorityCleaningTip>增加一个供殖民者清洁的区域。</AddAreaForPriorityCleaningTip>
  <CleaningAreaIsPrioritized>殖民者将清洁该区域。</CleaningAreaIsPrioritized>
  <OnlyCleaningArea>仅该区域将被清洁。</OnlyCleaningArea>
  <CleaningAreaFirst>该区域将优先被清洁。</CleaningAreaFirst>
  <CleaningAreaLast>该区域将最后被清洁。</CleaningAreaLast>
  <CleaningAreaMiddle>该区域将在{0}之后，{1}之前被清洁。</CleaningAreaMiddle>
</LanguageData>`

In DefInjected\JobDef\Jobs_Work.xml

`<?xml version="1.0" encoding="utf-8"?>
<LanguageData>
  <Clean_Prioritized.reportString>正在清理区域中的TargetA。</Clean_Prioritized.reportString>
</LanguageData>`

**Comment by emipa606** [comment]
Thanks, should be updated in 1f5e9eb
For future updates it would be great if you made a PR or at least attach the relevant files when creating the issue.
